---
title: Identifying the most divergent traits in the southeastern perennial clade in
  the Helianthus genus
author: "Sam Majumder"
date: "1/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(lattice)
library(ggplot2)
library(caret)
library(randomForest)
library(tidyverse)
```

```{r}

### Read in the training and test files ###

train <- read.csv("D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/train_imputed.csv")

test <- read.csv("D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/test_imputed.csv") 
```

```{r}
### Standardizing the data ###

train_new <- cbind(train[1], apply(train[2:72],2,scale)) 
test_new <- cbind(test[1], apply(test[2:72],2,scale))
```  


```{r}

##### keeping only the south eastern perennials ### 

train_new <- filter(train, Species == "H. carnosus" | Species == "H. atrorubens" | Species == "H. radula" | Species == "H. silphioides" | Species == "H. floridanus" | Species == "H. heterophyllus" | Species == "H. longifolius" | Species == "H. angustifolius")


test_new <- filter(test, Species == "H. carnosus" | Species == "H. atrorubens" | Species == "H. radula" | Species == "H. silphioides" | Species == "H. floridanus" | Species == "H. heterophyllus" | Species == "H. longifolius" | Species == "H. angustifolius")

```

```{r} 
#### converting the Species column to factor ### 

train_new$Species <- factor(train_new$Species)

test_new$Species <- factor(test_new$Species)

```


```{r}
##### WF1 (Workflow 1) ### Feature selection by Gini Impurity ### 
set.seed(1234)
Rf <- randomForest(Species~., data = train_new)

varImpPlot(Rf)

importance_by_gini <- varImp(Rf)

write.csv(importance_by_gini,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Gini/Feature_selection/Importance_by_gini_south_eastern_perennials.csv")


##### using only the top 30 variables as deemed by varImpPlot ### 
###

train_gini <- train_new[,c("Species","LCirc","LTD","LA","WPFB","WPTB","LDM","FPDM","WPFF","LeafC",
                               "WPLMF","LWC","LS","FRW","LFM","FPFM","FRN","LNRa","P.T","FTC","FRWC",
                               "LDMC","FPA","FTD","FPD","LD13C","P.D","FRL","FDAF","FRDM","Parea.T")]


test_gini <- test_new[,c("Species","LCirc","LTD","LA","WPFB","WPTB","LDM","FPDM","WPFF","LeafC",
                             "WPLMF","LWC","LS","FRW","LFM","FPFM","FRN","LNRa","P.T","FTC","FRWC",
                             "LDMC","FPA","FTD","FPD","LD13C","P.D","FRL","FDAF","FRDM","Parea.T")]


#### MODELLING ##### 
##### Random forests##

set.seed(1234)
params <- trainControl(method = "cv",
                       number = 5)



set.seed(1234)

Rf_gini <- train(Species~., data=train_gini,
                  method="rf",ntree= 500,trControl=params,
                  verbose=F,tuneGrid=data.frame(mtry=5))





p_rf_gini_train <- predict(Rf_gini,train_gini)

p_rf_gini <- predict(Rf_gini,test_gini)

c_rf_gini_train <- confusionMatrix(p_rf_gini_train,train_gini$Species)

c_rf_gini <- confusionMatrix(p_rf_gini,test_gini$Species)


###############    #### Random Forest ######## 

#### predicted vs reference ### 

pred_vs_ref_rf_gini <- data.frame(c_rf_gini$table)

### writing this dataframe out in a nice excel sheet ### 

write.csv(pred_vs_ref_rf_gini,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Gini/Modelling/Random_forest/pred_vs_ref.csv")

################

per_class_metrics_RF_gini <- data.frame(c_rf_gini$byClass)

### writing this dataframe out in a nice excel sheet ### 

write.csv(per_class_metrics_RF_gini,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Gini/Modelling/Random_forest/per_class_metrics_RF.csv")

#### Macro averaged metrics ### Random_forest ########

Macro_averaged_metrics_Rf <- data.frame(apply(per_class_metrics_RF_gini[-1],2,mean))

## renaming the column ### 

colnames(Macro_averaged_metrics_Rf) ### getting the name of the column 

names(Macro_averaged_metrics_Rf)[names(Macro_averaged_metrics_Rf) == "apply.per_class_metrics_RF_gini..1...2..mean."] <- "macro_averaged_metrics"

### Write it out in a nice excel sheet ### 

write.csv(Macro_averaged_metrics_Rf,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Gini/Modelling/Random_forest/macro_averaged_metrics_RF.csv")


#### GBM ### 

grid <- expand.grid(n.trees=c(600,1000),
                    interaction.depth=c(4,6),
                    shrinkage=0.1,
                    n.minobsinnode=10)


params <- trainControl(method = "cv",
                       number = 5)



set.seed(1234)

gbm_gini <- train(Species~., data=train_gini,
                  method="gbm",trControl=params,
                  verbose=T,tuneGrid=grid)


plot(gbm_gini)

gbm_gini

p_gbm_gini <- predict(gbm_gini,test_gini)

c_gbm_gini <- confusionMatrix(p_gbm_gini,test_gini$Species)

###############    #### GBM ######## 
#### predicted vs reference ### GBM

pred_vs_ref_gbm_gini <- data.frame(c_gbm_gini$table)

### writing this dataframe out in a nice excel sheet ### 

write.csv(pred_vs_ref_gbm_gini,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Gini/Modelling/GBM/pred_vs_ref.csv")

###########################

per_class_metrics_GBM_gini <- data.frame(c_gbm_gini$byClass)

### writing this dataframe out in a nice excel sheet ### 

write.csv(per_class_metrics_GBM_gini,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Gini/Modelling/GBM/per_class_metrics_GBM.csv")

#### Macro averaged metrics ### Random_forest ########

Macro_averaged_metrics_GBM <- data.frame(apply(per_class_metrics_GBM_gini[-1],2,mean))

## renaming the column ### 

colnames(Macro_averaged_metrics_GBM) ### getting the name of the column 

names(Macro_averaged_metrics_GBM)[names(Macro_averaged_metrics_GBM) == "apply.per_class_metrics_GBM_gini..1...2..mean."] <- "macro_averaged_metrics"

### Write it out in a nice excel sheet ### 

write.csv(Macro_averaged_metrics_GBM,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Gini/Modelling/GBM/macro_averaged_metrics_GBM.csv")

```

```{r}

### Model Comparison ###

model_list <- resamples(list(Rf=Rf_gini, GBM=gbm_gini))


bwplot(model_list)


```




```{r}

### WF2 (Workflow 2) ## Feature selection by RFE ### 

set.seed(1234)

subsets <- c(1:5,20,30)

params_rfe <- rfeControl(functions = rfFuncs,method = "cv",number = 5,verbose = T)

set.seed(1234)

features_2 <- rfe(Species~.,data = train_new,
                  sizes=subsets,rfeControl=params_rfe)


##### 

## Importance of each features ### 


variables <- data.frame(varImp(features_2))

### writing out this dataframe ### 

write.csv(variables,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/RFE/Feature_selection/RFE_south_eastern_perennial_importance.csv")


## variation of accuracy with the removal of variables ### 

features_2

results <- data.frame(features_2$results)

### writing out this dataframe ### 

write.csv(results,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/RFE/Feature_selection/RFE_south_eastern_perennial.csv")

predictors(features_2)

ggplot(features_2) 

plot(features_2, type = c("g", "o"))


######## Keeping only the top 5 variables 

train_rfe <- train_new[,c("Species","LCirc","LTD","LA","LWC","WPFB")]

test_rfe <- test_new[,c("Species","LCirc","LTD","LA","LWC","WPFB")]

#### MODELLING ##### 

##### Random forests##
set.seed(1234)
params <- trainControl(method = "cv",
                       number = 5)



set.seed(1234)

Rf_rfe <- train(Species~., data=train_rfe,
                  method="rf",ntree= 500,trControl=params,
                  verbose=F,tuneGrid=data.frame(mtry=5))



p_rf_rfe <- predict(Rf_rfe,test_rfe)

c_rf_rfe <- confusionMatrix(p_rf_rfe,test_rfe$Species)


##### Random forests##

params <- trainControl(method = "cv",
                       number = 5)



set.seed(1234)

Rf_rfe <- train(Species~., data=train_rfe,
                  method="rf",ntree= 500,trControl=params,
                  verbose=F,tuneGrid=data.frame(mtry=5))



p_rf_rfe <- predict(Rf_rfe,test_rfe)

c_rf_rfe <- confusionMatrix(p_rf_rfe,test_rfe$Species)

#########################
##############

###############    #### Random Forest ######## 
#### predicted vs reference ### 

pred_vs_ref_rf_rfe <- data.frame(c_rf_rfe$table)

### writing this dataframe out in a nice excel sheet ### 

write.csv(pred_vs_ref_rf_rfe,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/RFE/Modelling/Random_forest/pred_vs_ref.csv")

###########

per_class_metrics_RF_rfe <- data.frame(c_rf_rfe$byClass)

### writing this dataframe out in a nice excel sheet ### 

write.csv(per_class_metrics_RF_rfe,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/RFE/Modelling/Random_forest/per_class_metrics_RF.csv")

#### Macro averaged metrics ### Random_forest ########

Macro_averaged_metrics_Rf <- data.frame(apply(per_class_metrics_RF_rfe[-1],2,mean))

## renaming the column ### 

colnames(Macro_averaged_metrics_Rf) ### getting the name of the column 

names(Macro_averaged_metrics_Rf)[names(Macro_averaged_metrics_Rf) == "apply.per_class_metrics_RF_rfe..1...2..mean."] <- "macro_averaged_metrics"

### Write it out in a nice excel sheet ### 

write.csv(Macro_averaged_metrics_Rf,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/RFE/Modelling/Random_forest/macro_averaged_metrics_RF.csv")

#### GBM ### 

grid <- expand.grid(n.trees=c(600,1000),
                    interaction.depth=c(4,6),
                    shrinkage=0.1,
                    n.minobsinnode=10)


params <- trainControl(method = "cv",
                       number = 5)



set.seed(1234)

gbm_rfe <- train(Species~., data=train_rfe,
                 method="gbm",trControl=params,
                 verbose=T,tuneGrid=grid)


plot(gbm_rfe)

gbm_rfe

p_gbm_rfe <- predict(gbm_rfe,test_rfe)

c_gbm_rfe <- confusionMatrix(p_gbm_rfe,test_rfe$Species)

########################## 

###############    #### GBM ######## 

############## 

#### predicted vs reference ### GBM

pred_vs_ref_gbm_rfe <- data.frame(c_gbm_rfe$table)

### writing this dataframe out in a nice excel sheet ### 

write.csv(pred_vs_ref_gbm_rfe,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/RFE/Modelling/GBM/pred_vs_ref.csv")

###############

per_class_metrics_GBM_rfe <- data.frame(c_gbm_rfe$byClass)

### writing this dataframe out in a nice excel sheet ### 

write.csv(per_class_metrics_GBM_rfe,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/RFE/Modelling/GBM/per_class_metrics_GBM.csv")

#### Macro averaged metrics ### Random_forest ########

Macro_averaged_metrics_GBM <- data.frame(apply(per_class_metrics_GBM_rfe[-1],2,mean))

## renaming the column ### 

colnames(Macro_averaged_metrics_GBM) ### getting the name of the column 

names(Macro_averaged_metrics_GBM)[names(Macro_averaged_metrics_GBM) == "apply.per_class_metrics_GBM_rfe..1...2..mean."] <- "macro_averaged_metrics"

### Write it out in a nice excel sheet ### 

write.csv(Macro_averaged_metrics_GBM,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/RFE/Modelling/GBM/macro_averaged_metrics_GBM.csv")

```

```{r}
### Model Comparison ###

model_list <- resamples(list(Rf=Rf_rfe, GBM=gbm_rfe))


bwplot(model_list)

```


```{r}
####### 
#### WF3 (Workflow 3) ## Feature selection by Boruta (Wrapper) ## Modelling by Decision Trees, Random Forest and Gradient Boosting Machine 

library(Boruta)

set.seed(1234)

Imp_feature <- Boruta(Species~., data = train_new, doTrace=2, maxRuns=500)
attStats(Imp_feature)                     ### viewing which attributes are important 

## Putting the importance decisions in a nice table ### 

Boruta_feature_analysis <- data.frame(attStats(Imp_feature)) 

####### 
### writing out this file #### 

write.csv(Boruta_feature_analysis,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Boruta/Feature_selection/Boruta_south_eastern_perennials_results.csv")

###### Removing the unimportant variables and keeping only the important ones ### 
### 67 important variables ####

train_boruta <- train_new[,-c(4,21,22,30)]

test_boruta <- test_new[,-c(4,21,22,30)]


#### MODELLING ### 67 Features are important ###

##### Random forests##
set.seed(1234)
params <- trainControl(method = "cv",
                       number = 5)



set.seed(1234)

Rf_boruta <- train(Species~., data=train_boruta,
                  method="rf",ntree= 500,trControl=params,
                  verbose=F,tuneGrid=data.frame(mtry=5))


p_rf_boruta <- predict(Rf_boruta,test_boruta)

c_rf_boruta <- confusionMatrix(p_rf_boruta,test_boruta$Species)


###############    #### Random Forest ######## 

#### predicted vs reference ### 

pred_vs_ref_rf_boruta <- data.frame(c_rf_boruta$table)

### writing this dataframe out in a nice excel sheet ### 

write.csv(pred_vs_ref_rf_boruta,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Boruta/Modelling/Random_forest/pred_vs_ref.csv")

#################

per_class_metrics_RF_boruta <- data.frame(c_rf_boruta$byClass)

### writing this dataframe out in a nice excel sheet ### 

write.csv(per_class_metrics_RF_boruta,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Boruta/Modelling/Random_forest/per_class_metrics_RF.csv")

#### Macro averaged metrics ### Random_forest ########

Macro_averaged_metrics_Rf <- data.frame(apply(per_class_metrics_RF_boruta[-1],2,mean))

## renaming the column ### 

colnames(Macro_averaged_metrics_Rf) ### getting the name of the column 

names(Macro_averaged_metrics_Rf)[names(Macro_averaged_metrics_Rf) == "apply.per_class_metrics_RF_boruta..1...2..mean."] <- "macro_averaged_metrics"

### Write it out in a nice excel sheet ### 

write.csv(Macro_averaged_metrics_Rf,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Boruta/Modelling/Random_forest/macro_averaged_metrics_RF.csv")



#### GBM ### 

grid <- expand.grid(n.trees=c(600,1000),
                    interaction.depth=c(4,6),
                    shrinkage=0.1,
                    n.minobsinnode=10)


params <- trainControl(method = "cv",
                       number = 5)



set.seed(1234)

gbm_boruta <- train(Species~., data=train_boruta,
                    method="gbm",trControl=params,
                    verbose=T,tuneGrid=grid)


plot(gbm_boruta)

gbm_boruta

p_gbm_boruta <- predict(gbm_boruta,test_boruta)

c_gbm_boruta <- confusionMatrix(p_gbm_boruta,test_boruta$Species)

###############    #### GBM ######## 

#### predicted vs reference ### GBM

pred_vs_ref_gbm_boruta <- data.frame(c_gbm_boruta$table)

### writing this dataframe out in a nice excel sheet ### 

write.csv(pred_vs_ref_gbm_boruta,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Boruta/Modelling/GBM/pred_vs_ref.csv")

#####################

per_class_metrics_GBM_boruta <- data.frame(c_gbm_boruta$byClass)

### writing this dataframe out in a nice excel sheet ### 

write.csv(per_class_metrics_GBM_boruta,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Boruta/Modelling/GBM/per_class_metrics_GBM.csv")

#### Macro averaged metrics ### Random_forest ########

Macro_averaged_metrics_GBM <- data.frame(apply(per_class_metrics_GBM_boruta[-1],2,mean))

## renaming the column ### 

colnames(Macro_averaged_metrics_GBM) ### getting the name of the column 

names(Macro_averaged_metrics_GBM)[names(Macro_averaged_metrics_GBM) == "apply.per_class_metrics_GBM_boruta..1...2..mean."] <- "macro_averaged_metrics"

### Write it out in a nice excel sheet ### 

write.csv(Macro_averaged_metrics_GBM,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_1/South_eastern_perennial/Boruta/Modelling/GBM/macro_averaged_metrics_GBM.csv")

```

```{r}
### Model Comparison ###

model_list <- resamples(list(Rf=Rf_boruta, GBM=gbm_boruta))


bwplot(model_list)
```

















